-- Sipher Web Template - Direct Database Insert
-- Run this SQL script to add the template to your database

USE website_builder;

-- Insert Sipher Web Template
INSERT INTO website_templates (
    template_name,
    description,
    author,
    section_count,
    sections_json,
    page_count,
    tags,
    category
) VALUES (
    'Sipher Web - E-Commerce Agency',
    'Professional tech agency website with glass morphism design, featuring hero section with coding background, feature cards, and modern navigation. Perfect for tech companies, SaaS platforms, and digital agencies.',
    'Claude Code',
    4,
    '[
        {
            "id": 1,
            "type": 1,
            "name": "Top Announcement Bar",
            "section_id": "top-bar",
            "y_position": 0,
            "height": 50,
            "selected": false,
            "title": "Trusted by 100+ Enterprise Clients Worldwide  |  Delivering innovation & Excellence Since 2022  |  Contact Us: +91 8318230713",
            "subtitle": "",
            "content": "",
            "button_text": "",
            "button_link": "",
            "title_font_size": 14,
            "subtitle_font_size": 16,
            "content_font_size": 16,
            "title_font_weight": 400,
            "subtitle_font_weight": 400,
            "content_font_weight": 400,
            "title_color": [1.0, 1.0, 1.0, 1.0],
            "subtitle_color": [1.0, 1.0, 1.0, 0.9],
            "content_color": [1.0, 1.0, 1.0, 0.8],
            "background_image": "",
            "section_image": "",
            "bg_texture_id": 0,
            "img_texture_id": 0,
            "use_bg_image": false,
            "bg_overlay_opacity": 0.5,
            "bg_color": [0.102, 0.102, 0.302, 1.0],
            "text_color": [1.0, 1.0, 1.0, 1.0],
            "accent_color": [1.0, 0.549, 0.0, 1.0],
            "button_bg_color": [1.0, 0.549, 0.0, 1.0],
            "button_text_color": [1.0, 1.0, 1.0, 1.0],
            "button_font_size": 16,
            "button_font_weight": 500,
            "padding": 12,
            "text_align": 1,
            "button_glass_effect": false,
            "button_glass_opacity": 0.3,
            "button_glass_tint": [1.0, 1.0, 1.0, 1.0],
            "layout_style": 0
        },
        {
            "id": 2,
            "type": 1,
            "name": "Navigation Bar",
            "section_id": "navbar",
            "y_position": 50,
            "height": 80,
            "selected": false,
            "title": "Sipher Web Pvt. Ltd.",
            "subtitle": "",
            "content": "",
            "button_text": "",
            "button_link": "",
            "title_font_size": 24,
            "subtitle_font_size": 16,
            "content_font_size": 16,
            "title_font_weight": 700,
            "subtitle_font_weight": 400,
            "content_font_weight": 400,
            "title_color": [0.051, 0.051, 0.227, 1.0],
            "subtitle_color": [0.3, 0.3, 0.3, 1.0],
            "content_color": [0.2, 0.2, 0.2, 1.0],
            "background_image": "",
            "section_image": "",
            "bg_texture_id": 0,
            "img_texture_id": 0,
            "use_bg_image": false,
            "bg_overlay_opacity": 0.5,
            "bg_color": [1.0, 1.0, 1.0, 1.0],
            "text_color": [0.051, 0.051, 0.227, 1.0],
            "accent_color": [1.0, 0.549, 0.0, 1.0],
            "button_bg_color": [1.0, 0.549, 0.0, 1.0],
            "button_text_color": [1.0, 1.0, 1.0, 1.0],
            "button_font_size": 16,
            "button_font_weight": 500,
            "padding": 20,
            "text_align": 0,
            "nav_bg_color": [1.0, 1.0, 1.0, 1.0],
            "nav_text_color": [0.051, 0.051, 0.227, 1.0],
            "nav_font_size": 16,
            "nav_font_weight": 500,
            "nav_items": [
                {"label": "Home", "link": "#home", "target_page": "", "target_section": "home", "text_color": [1.0, 0.549, 0.0, 1.0], "font_size": 16, "font_weight": 500},
                {"label": "Company", "link": "#company", "target_page": "", "target_section": "company", "text_color": [0.051, 0.051, 0.227, 1.0], "font_size": 16, "font_weight": 500},
                {"label": "Services", "link": "#services", "target_page": "", "target_section": "services", "text_color": [0.051, 0.051, 0.227, 1.0], "font_size": 16, "font_weight": 500},
                {"label": "Products", "link": "#products", "target_page": "", "target_section": "products", "text_color": [0.051, 0.051, 0.227, 1.0], "font_size": 16, "font_weight": 500},
                {"label": "Portfolio", "link": "#portfolio", "target_page": "", "target_section": "portfolio", "text_color": [0.051, 0.051, 0.227, 1.0], "font_size": 16, "font_weight": 500},
                {"label": "Blog", "link": "#blog", "target_page": "", "target_section": "blog", "text_color": [0.051, 0.051, 0.227, 1.0], "font_size": 16, "font_weight": 500},
                {"label": "Contact", "link": "#contact", "target_page": "", "target_section": "contact", "text_color": [0.051, 0.051, 0.227, 1.0], "font_size": 16, "font_weight": 500}
            ],
            "layout_style": 0
        },
        {
            "id": 3,
            "type": 0,
            "name": "Hero - E-Commerce Excellence",
            "section_id": "hero",
            "y_position": 130,
            "height": 850,
            "selected": false,
            "title": "E-Commerce Excellence",
            "subtitle": "Powerful e-commerce solutions with seamless payment processing, inventory management, and customer analytics.",
            "content": "Transform your online store with our cutting-edge technology platform designed for growth and scalability.",
            "button_text": "Transform Your Store →",
            "button_link": "#transform",
            "title_font_size": 56,
            "subtitle_font_size": 20,
            "content_font_size": 18,
            "title_font_weight": 700,
            "subtitle_font_weight": 400,
            "content_font_weight": 400,
            "title_color": [1.0, 1.0, 1.0, 1.0],
            "subtitle_color": [1.0, 1.0, 1.0, 0.9],
            "content_color": [1.0, 1.0, 1.0, 0.8],
            "background_image": "",
            "section_image": "",
            "bg_texture_id": 0,
            "img_texture_id": 0,
            "use_bg_image": false,
            "bg_overlay_opacity": 0.85,
            "bg_color": [0.051, 0.051, 0.227, 1.0],
            "text_color": [1.0, 1.0, 1.0, 1.0],
            "accent_color": [1.0, 0.549, 0.0, 1.0],
            "button_bg_color": [1.0, 1.0, 1.0, 1.0],
            "button_text_color": [0.051, 0.051, 0.227, 1.0],
            "button_font_size": 18,
            "button_font_weight": 600,
            "padding": 120,
            "text_align": 1,
            "button_glass_effect": false,
            "button_glass_opacity": 0.3,
            "button_glass_tint": [1.0, 1.0, 1.0, 1.0],
            "layout_style": 0
        },
        {
            "id": 4,
            "type": 4,
            "name": "Feature Cards",
            "section_id": "features",
            "y_position": 980,
            "height": 400,
            "selected": false,
            "title": "Why Choose Us",
            "subtitle": "Built for the modern digital economy",
            "content": "",
            "button_text": "",
            "button_link": "",
            "title_font_size": 42,
            "subtitle_font_size": 20,
            "content_font_size": 16,
            "title_font_weight": 700,
            "subtitle_font_weight": 400,
            "content_font_weight": 400,
            "title_color": [1.0, 1.0, 1.0, 1.0],
            "subtitle_color": [1.0, 1.0, 1.0, 0.8],
            "content_color": [1.0, 1.0, 1.0, 0.7],
            "background_image": "",
            "section_image": "",
            "bg_texture_id": 0,
            "img_texture_id": 0,
            "use_bg_image": false,
            "bg_overlay_opacity": 0.5,
            "bg_color": [0.051, 0.051, 0.227, 1.0],
            "text_color": [1.0, 1.0, 1.0, 1.0],
            "accent_color": [1.0, 0.549, 0.0, 1.0],
            "button_bg_color": [1.0, 0.549, 0.0, 1.0],
            "button_text_color": [1.0, 1.0, 1.0, 1.0],
            "button_font_size": 16,
            "button_font_weight": 500,
            "padding": 80,
            "text_align": 1,
            "cards": [
                {
                    "title": "Secure",
                    "description": "Protected Payments",
                    "image": "",
                    "price": "",
                    "link": "",
                    "bg_color": [0.102, 0.102, 0.302, 0.5],
                    "title_color": [1.0, 1.0, 1.0, 1.0],
                    "description_color": [1.0, 1.0, 1.0, 0.7]
                },
                {
                    "title": "Analytics",
                    "description": "Data Insights",
                    "image": "",
                    "price": "",
                    "link": "",
                    "bg_color": [0.102, 0.102, 0.302, 0.5],
                    "title_color": [1.0, 1.0, 1.0, 1.0],
                    "description_color": [1.0, 1.0, 1.0, 0.7]
                },
                {
                    "title": "Scalable",
                    "description": "Growth Ready",
                    "image": "",
                    "price": "",
                    "link": "",
                    "bg_color": [0.102, 0.102, 0.302, 0.5],
                    "title_color": [1.0, 1.0, 1.0, 1.0],
                    "description_color": [1.0, 1.0, 1.0, 0.7]
                }
            ],
            "cards_columns": 3,
            "cards_gap": 30,
            "layout_style": 0
        }
    ]',
    1,
    'tech, agency, e-commerce, glass morphism, modern, professional, sipher web',
    'Technology / Agency'
);

-- Verify the insert
SELECT id, template_name, section_count, created_date
FROM website_templates
WHERE template_name = 'Sipher Web - E-Commerce Agency';
